name        = "bopy"
name8       = "bopy"
locale      = "fr"
variant     = "bopy"
description = "bopy"
author      = "Malekpe"
url         = "https://github.com/malekpe/Beopy-L"
geometry    = "ERGO"
version     = "1.2.5"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ |   ┃ € ‚ │ « ‘ │ » ’ │ $   │ %   ┃ ^   │ &   │ *   │ #   │ @   ┃ ≠   ┆ ÷   ┆
┆ ^   ┃ 1 „ │ 2 “ │ 3 ” │ 4 ¢ │ 5 ‰ ┃ 6 ¥ │ 7 ¤ │ 8 § │ 9 ¶ │ 0 ° ┃ =   ┆ /   ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ B*µ │ ! ¡ │ O _ │ P   │ Y   ┃ ? ¿ │ V   │ D   │ L   │ J   ┃ ±   ┆ ×   ┆
·     ┃  *µ │***¨ │   _ │   ê │   – ┃ - ‑ │   # │   ö │  *^ │   ñ ┃ +   ┆ *   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ U   │ E   │ I   │ ; • ┃ C   │ T   │ S   │ R   │ N   ┃ "   ┆ ~   ┆
·     ┃   æ │     │   é │   è │ , · ┃   ç │   à │   ß │   ü │   ä ┃ '   ┆ `   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ >   ┃ K   │ Z   │ X   │ : ⋯ │ W   ┃ M   │ G   │ Q   │ H   │ F   ┃           ·
┆ <   ┃     │     │     │ . … │   — ┃     │   & │   œ │   ù │     ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │   ≤ │   ≥ │  *¤ │   ‰ ┃  *^ │     │   × │  *´ │  *` ┃     ┆     ┆
·     ┃   @ │   < │   > │   $ │   % ┃   ^ │   & │   * │   ' │   ` ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *ˇ │   ⁽ │   ⁾ │     │   ≠ ┃  *~ │   ± │  *¯ │   – │  *¨ ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   ~ │   + │   - │   _ │   " ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  */ │     │     │   ÷ │     ┃   ¦ │   ¬ │  *¸ │     │     ┃           ·
┆     ┃   \ │   [ │   ] │   / │   # ┃   | │   ! │   ; │   : │   ? ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u0027"  # '
1dk_shift   = "\u2019"  # RIGHT SINGLE QUOTATION MARK
